### ISSUE TITLE
Terminal no longer sending output to USB.

### ISSUE THREAD

**Issue by Clocktim3r** [ryu10/M5CardForth#4]
USB terminal used to show output. After re-flashing recently, I can still input keyboard commands to terminal, but output goes to LCD screen. I would love to understand what has changed.

**Comment by ryu10** [comment]
> [...] output goes to LCD screen

This is the default behavior. [Please see the Console section of Readme.](https://github.com/ryu10/M5CardForth?tab=readme-ov-file#console)

To switch the console output to serial, type: `m5type-off`. You can also write`m5type-off` in [/spiffs/autoexec.fs](https://github.com/ryu10/M5CardForth/blob/main/forth/autoexec.fs).

**Comment by Clocktim3r** [comment]
If I reply to this, do you see it?

I just have one question. I wonder if this was always the behavior? I swear
I remember unless I press button Btn0 that only the orange text shown on
the LCD.

I now understand how to make it work how remember. On line 3080 in main,
add m5type-off after m5key-off.

Thank you for your time helping through my confusion.

**Comment by ryu10** [comment]
Glad to hear that you solved the issue.

I haven't updated the code since January 2024 (shame on me). So the behavior is unchanged for a long time. 

The BTNG0 trick at startup is used only to switch the key-in routing. It does not affect the LCD output. 
To modify the I/O routing permanently, it's the best to rewrite the startup code, like you did.

**Comment by Clocktim3r** [comment]
This project inspires me. Thank you for putting it together and thank you
again for your attention.
